# Generated by Django 3.1.6 on 2021-03-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadSourceCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('filePath', models.FileField(upload_to='sourceCodeFiles/', verbose_name='filePath')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('parameter', models.CharField(max_length=100, verbose_name='parameter')),
            ],
        ),
        migrations.CreateModel(
            name='uploadSourceProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('filePath', models.FileField(upload_to='sourceProgramFiles/', verbose_name='filePath')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('parameter', models.CharField(max_length=100, verbose_name='parameter')),
                ('compileCommand', models.CharField(max_length=100, verbose_name='compileCommand')),
            ],
        ),
    ]
