# Generated by Django 3.1.6 on 2021-03-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadSourceCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('filePath', models.FileField(upload_to='sourceCodeFiles/', verbose_name='filePath')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('ins', models.FileField(upload_to='seeddir/', verbose_name='seeddir')),
                ('inputFile', models.FileField(upload_to='inputFile/', verbose_name='inputFile')),
                ('compileCommand', models.CharField(default='', max_length=100, verbose_name='compileCommand')),
                ('parameter', models.CharField(default='', max_length=100, verbose_name='parameter')),
                ('inputCommand', models.TextField(default='', max_length=500, verbose_name='inputCommand')),
            ],
        ),
        migrations.CreateModel(
            name='uploadSourceProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('filePath', models.FileField(upload_to='sourceProgramFiles/', verbose_name='filePath')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('parameter', models.CharField(default='', max_length=100, verbose_name='parameter')),
                ('ins', models.FileField(upload_to='seeddir/', verbose_name='seeddir')),
                ('inputCommand', models.TextField(default='', max_length=500, verbose_name='inputCommand')),
                ('inputFile', models.FileField(upload_to='inputFile/', verbose_name='inputFile')),
            ],
        ),
    ]
