# Generated by Django 3.1.6 on 2021-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210315_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsourcecode',
            name='inputCommand',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='inputCommand'),
        ),
        migrations.AlterField(
            model_name='uploadsourcecode',
            name='ins',
            field=models.TextField(blank=True, max_length=500, verbose_name='seeddir'),
        ),
        migrations.AlterField(
            model_name='uploadsourcecode',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='parameter'),
        ),
        migrations.AlterField(
            model_name='uploadsourceprogram',
            name='inputCommand',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='inputCommand'),
        ),
        migrations.AlterField(
            model_name='uploadsourceprogram',
            name='ins',
            field=models.TextField(blank=True, max_length=1000, verbose_name='seeddir'),
        ),
        migrations.AlterField(
            model_name='uploadsourceprogram',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='parameter'),
        ),
    ]
