# Generated by Django 3.2.5 on 2021-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210712_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsourcecode',
            name='parameter',
        ),
        migrations.AddField(
            model_name='uploadsourcecode',
            name='postPara',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='postPara'),
        ),
        migrations.AddField(
            model_name='uploadsourcecode',
            name='prePara',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='prePara'),
        ),
    ]
