# Generated by Django 3.1.6 on 2021-03-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210324_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsourcecode',
            name='ins',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='seeddir'),
        ),
    ]
