version: '3'
services:
  nginx:
    image: nginx  #需要nginx镜像，所以最好在本地事先生成一个nginx镜像
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  #做配置映射
    depends_on:
        - fuzzing
    ports:
        - "10801:80"
    restart: always

  fuzzing:
    build:
      context: ./BackEnd
      dockerfile: ./Dockerfile
    ports:
      - '10802:10802'
    volumes:
      - './BackEnd:/app'
    logging:
      driver: json-file
      options:
        max-size: 1g
    restart: always
